# Generated by Django 4.1.4 on 2023-02-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qpaper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tours',
            name='limited_days',
        ),
        migrations.AddField(
            model_name='tours',
            name='offerlimited',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
