# Generated by Django 4.1.4 on 2023-02-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qpaper', '0002_remove_tours_limited_days_tours_offerlimited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tours',
            old_name='discount_amount',
            new_name='discount_percent',
        ),
    ]
