# Generated by Django 4.1.4 on 2023-02-06 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Qpaper', '0003_rename_discount_amount_tours_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tours',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
