# Generated by Django 4.1.4 on 2023-02-14 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qpaper', '0004_tours_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Qpaper.tours'),
        ),
    ]
