# Generated by Django 4.1.4 on 2023-02-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qpaper', '0005_tourbooking_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tours',
            old_name='description',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='tours',
            name='location',
        ),
    ]
