# Generated by Django 4.1.4 on 2023-02-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qpaper', '0006_rename_description_tours_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourbooking',
            old_name='location',
            new_name='hote_add',
        ),
    ]
