# Generated by Django 4.1.4 on 2023-02-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qpaper', '0008_alter_tourbooking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='numberofrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
